# Tasks to deploy AWS infra to support CNS (COnatiner Native Storage)
---
- name: Create CNS Security Group for the new VPC
  ec2_group:
    aws_access_key: "{{ aws_access_key }}"
    aws_secret_key: "{{ aws_secret_key }}"
    name: "ocp-cns"
    description: "OCP CNS"
    vpc_id: "{{ new_vpc.vpc.id }}"
    region: "{{ aws_region }}"
    state: "present"
    tags:
      env_id: "{{ env_id }}"
    rules:
      - proto: tcp
        from_port: 24007
        to_port: 24007
        cidr_ip: 0.0.0.0/0
      - proto: tcp
        from_port: 24008
        to_port: 24008
        cidr_ip: 0.0.0.0/0
      - proto: tcp
        from_port: 2222
        to_port: 2222
        cidr_ip: 0.0.0.0/0
      - proto: tcp
        from_port: 49152
        to_port: 49664
        cidr_ip: 0.0.0.0/0
      - proto: tcp
        from_port: 24010
        to_port: 24010
        cidr_ip: 0.0.0.0/0
      - proto: tcp
        from_port: 3260
        to_port: 3260
        cidr_ip: 0.0.0.0/0
      - proto: tcp
        from_port: 111
        to_port: 111
        cidr_ip: 0.0.0.0/0
  register: cns_sg

- name: Create Gluster Nodes
  ec2:
    image: "{{ aws_image_name }}"
    instance_type: "{{ gluster_flavor | default('i3.xlarge') }}"
    group: "{{ aws_gluster_sgroups }}"
    termination_protection: "{{ instances_termination_protection }}"
    key_name: "{{ aws_key_name }}"
    aws_access_key: "{{ aws_access_key }}"
    aws_secret_key: "{{ aws_secret_key }}"
    region: "{{ aws_region }}"
    vpc_subnet_id: "{{ aws_subnet }}"
    exact_count: 1
    wait: yes
    count_tag:
      Name: "{{ env_id }}-ocp-cns-{{ item }}"
    instance_tags:
      Name: "{{ env_id }}-ocp-cns-{{ item }}"
      user: "{{ user_tag }}"
      role: "{{ role_tag }}"
      group: "{{ group_gluster_tag }}"
      node_labels: "{{ labels_cns_tag }}"
      ocp_role: "{{ gluster_tag }}"
      env_id: "{{ env_id }}"
    volumes:
      - device_name: /dev/sda1
        volume_type: gp2
        volume_size: "{{ gluster_root_volume_size | default('50') }}"
        tags:
          user: "{{ user_tag }}"
          role: "{{ role_tag }}"
          env_id: "{{ env_id }}"
      - device_name: "{{ docker_storage_block_device }}"
        volume_type: gp2
        volume_size: "{{ docker_volume_size | default('40') }}"
        tags:
          user: "{{ user_tag }}"
          role: "{{ role_tag }}"
          env_id: "{{ env_id }}"
      - device_name: "{{ gluster_storage_block_device }}"
        volume_type: gp2
        volume_size: "{{ gluster_volume_size | default('200') }}"
        tags:
          user: "{{ user_tag }}"
          role: "{{ role_tag }}"
          env_id: "{{ env_id }}"
  with_sequence:
    count=3
  register: instances_gluster

- name: Register new created objects as facts
  set_fact:
    cns_instances: "{{ instances_gluster }}"
