---
default_registry_auth_layer: false
default_registry_certificate_subject: "/C=US/ST=NC/L=Raleigh/O=Example, Inc/OU=Web/CN=example.com"
default_registry_domain_name: registry.example.com
nexus_repo_url: "http://nginx.org/packages/rhel/7/noarch/RPMS/nginx-release-rhel-7-0.el7.ngx.noarch.rpm"
