---  
- name: Register Environment Variable
  set_fact:
      env_id: "{{ env_id }}-{{ env_random_id.stdout }}"
      
- name: Validate OpenStack Variable
  fail: msg="Required OpenStack Variables not defined!"
  when: 
       - openstack_image_name is not defined
       - openstack_security_groups is not defined
       - openstack_key_name is not defined
       
- name: Provision OpenStack Master
  nova_compute:
    name: "{{ item }}"
    state: present
    image_name: "{{ openstack_image_name }}"
    flavor_id: "{{ openstack_flavor_id }}"
    key_name: "{{ openstack_key_name }}"
    security_groups: "{{ openstack_master_security_group }}"
    wait_for: 200
  with_items:
  -  "master-{{ env_id }}"
  register: nova_compute_masters
  
- add_host:
    hostname: "{{ item.info.name }}"
    ansible_ssh_host: "{{ item.public_ip }}"
    ansible_ssh_user: root
    groups: nova_compute_masters
  with_items: nova_compute_masters.results

- name: Wait for Master to be available
  wait_for: port=22 host={{ item.public_ip }}
  with_items: nova_compute_masters.results


- name: Provision OpenStack Nodes
  nova_compute:
    name: "node{{ item }}-{{ env_id }}"
    state: present
    image_name: "{{ openstack_image_name }}"
    flavor_id: "{{ openstack_flavor_id }}"
    key_name: "{{ openstack_key_name }}"
    security_groups: "{{ openstack_node_security_group }}"
    wait_for: 200
  with_sequence: start=1 end={{ openshift_node_count }}
  register: nova_compute_nodes

- add_host:
    hostname: "{{ item.info.name }}"
    ansible_ssh_host: "{{ item.public_ip }}"
    ansible_ssh_user: root
    groups: nova_compute_nodes
  with_items: nova_compute_nodes.results

- name: Wait for Nodes to be available
  wait_for: port=22 host={{ item.public_ip }}
  with_items: nova_compute_nodes.results
  
# Create Master Volumes
- include: create-volume.yml 
  vars:
    instance_type: "Master"
    openstack_machines: "{{ nova_compute_masters }}"
    volume_size: "{{ openstack_master_storage }}"

# Create Node Volumes
- include: create-volume.yml 
  vars:
    instance_type: "Node"
    openstack_machines: "{{ nova_compute_nodes }}"
    volume_size: "{{ openstack_node_storage }}"
