---
default_openshift_openstack_security_groups:
  - name: ose3_master
    type: master
    rules:
    - name: ssh
      from_port: 22
      to_port: 22
      protocol: tcp
      cidr: 0.0.0.0/0
    - name: http
      from_port: 80
      to_port: 80
      protocol: tcp
      cidr: 0.0.0.0/0
    - name: https
      from_port: 443
      to_port: 443
      protocol: tcp
      cidr: 0.0.0.0/0
    - name: https-8443
      from_port: 8443
      to_port: 8443
      protocol: tcp
      cidr: 0.0.0.0/0
  - name: ose3_nodes
    type: node
    rules:
    - name: ssh
      from_port: 22
      to_port: 22
      protocol: tcp
      cidr: 0.0.0.0/0
    - name: http
      from_port: 80
      to_port: 80
      protocol: tcp
      cidr: 0.0.0.0/0
  - name: dns
    type: dns
    rules:
    - name: dns
      from_port: 53
      to_port: 53
      protocol: udp
      cidr: 0.0.0.0/0
