---
- name: Setting Common Facts
  set_fact:
    openshift_storage_disk_volume: "{{ openshift_storage_disk_volume | default(default_openshift_storage_disk_volume) }}"
    openshift_storage_volume_size: "{{ openshift_storage_volume_size | default(default_openshift_storage_volume_size) }}"
    openshift_etcd_size: "{{ openshift_etcd_size | default(default_openshift_etcd_size) }}"
    openshift_logging_volume_size: "{{ openshift_logging_volume_size | default(default_openshift_logging_volume_size) }}"
    openshift_node_count: "{{ openshift_node_count | default(default_openshift_node_count) }}"
    env_id: "{{ env_id | default(default_env_id) }}-{{ env_random_id.stdout }}"