---

- name: "Prepend '-n' to the namespace, unless already set"
  set_fact:
    namespace_param: "{% if ((target_namespace|trim).find('-n') != 0) %}-n {% endif %}{{ target_namespace }}"
  when:
    - target_namespace|length > 0

- name: "Lookup route url for {{ route }}"
  shell: "oc get route {{ route }} -o jsonpath='{ .spec.host }' {{ namespace_param }}"
  register: url
  when:
  - route is defined
  - route|trim != ''

- name: "Set default delay time"
  set_fact:
    delay: "{{ delay | default(5) }}"

- name: "Set default number of retries"
  set_fact:
    retries: "{{ retries | default(3) }}"

- name: "Wait for {{ protocol }}://{{ url.stdout }} to respond with status: {{ status }}"
  uri:
    url: "{{ protocol }}://{{ url.stdout }}"
  register: rc
  until: rc.status|trim|int == status|trim|int
  retries: "{{ retries|int }}"
  delay: "{{ delay|int }}"
  when:
  - url.stdout is defined
  - url.stdout|trim != ''
  - protocol is defined
  - protocol|trim != ''
  - status is defined
  - status|trim != ''
